services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: vvleonid/docker-project-74:latest
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/mydb

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data
    # ports:
    #   - "5432:5432"
    restart: always

volumes:
  db_data: {}
